version: '3'
services:
  # Create frontend container
  frontend: # Name of our service
    build: ./frontend # path to dockerfile
    ports: # Port binding to host from docker container
      - "3000:3000" # Bind port 3000 of host to 3000 of container
    container_name: frontend-docker
    restart: always # What to do if container crashes
    links:
      - backend
  # Create backend container
  backend:
    # Create backend container  
    build: ./backend
    ports:
      - "3001:3001"
    container_name: backend-docker
    restart: always
  
  sendemail:
    # Create backend container  
    build: ./sendemail
    ports:
      - "3002:3002"
    container_name: sendemail-docker
    restart: always